# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
    env(APP_SECRET): '2036b15663b5a4fdb85b9d5c2c9298e2'
    env(REDIS_DSN): 'redis://blue-redis'
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    serializer:
        name_converter: serializer.name_converter.camel_case_to_snake_case
        circular_reference_handler: BlueGrid\Service\SerializationCircularReferenceHandler
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
