services:
  # Attribute mapping driver for the Doctrine Extension listeners
  gedmo.mapping.driver.attribute:
    class: Gedmo\Mapping\Driver\AttributeReader

  # Gedmo Tree Extension Listener
  gedmo.listener.tree:
    class: Gedmo\Tree\TreeListener
    tags:
      - { name: doctrine.event_listener, event: 'prePersist'}
      - { name: doctrine.event_listener, event: 'preUpdate'}
      - { name: doctrine.event_listener, event: 'preRemove'}
      - { name: doctrine.event_listener, event: 'onFlush'}
      - { name: doctrine.event_listener, event: 'loadClassMetadata'}
      - { name: doctrine.event_listener, event: 'postPersist'}
      - { name: doctrine.event_listener, event: 'postUpdate'}
      - { name: doctrine.event_listener, event: 'postRemove'}
    calls:
      # Uncomment the below call if using attributes, and comment the call for the annotation reader
       - [ setAnnotationReader, [ '@gedmo.mapping.driver.attribute' ] ]
      # The `annotation_reader` service was deprecated in Symfony 6.4 and removed in Symfony 7.0
#      - [ setAnnotationReader, [ '@annotation_reader' ] ]