name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Build the Docker image
        run: sudo docker compose -f docker-compose.yml -f docker-compose-dev.yml up -d --quiet-pull

      - name: Install dependencies
        run: sudo docker compose -f docker-compose.yml -f docker-compose-dev.yml exec -T php composer install --no-interaction

      - name: Code check
        run: sudo docker compose -f docker-compose.yml -f docker-compose-dev.yml exec -T php make code-check

      - name: Tests
        run: sudo docker compose -f docker-compose.yml -f docker-compose-dev.yml exec -T php make test
